# -*- coding: utf-8 -*-
"""Copy of Introducción_a_Web_Semántica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iawrW9IX_f1QWzL_yDAA6ubaJiAYqfyl

# Introducción a RDF

En esta sección, se va a introducir RDF. Para ello, se requiere instalar la  librería [rdflib](https://rdflib.readthedocs.io/).
"""

# !pip install rdflib

"""A partir de ahí, se pueden crear grafos importando las clases correspondientes de rdflib."""

from rdflib import Graph

g = Graph()

g.parse("https://raw.githubusercontent.com/cursosLabra/pruebawebsem/main/example1.ttl", format="turtle")

for contador, t in enumerate(g):
  print(f"Tripleta {contador}: sujeto = {t[0]}, predicado = {t[1]}, objeto = {t[2]}")

print(g.serialize(format="nt"))

print(g.serialize(format="xml"))

print(g.serialize(format="json-ld"))

g.parse("https://raw.githubusercontent.com/cursosLabra/pruebawebsem/main/example2.ttl", format="turtle")
print(g.serialize(format="turtle"))